### ISSUE TITLE
wrong file path for colormap

### ISSUE THREAD

**Issue by VeryBitter** [kuadrat/arpys#11]
Hello,
I am new to arpes data processing. So I am trying to figure out how the arpys package works.
It seems to me that file paths in the plotting.py file are not correct as they point towards "/home/kevin/bin/kustom/cmaps/rainbow_light.dat" and so on.

Cheers

Aristide

**Comment by kuadrat** [comment]
Hi, thanks for pointing it out! In fact, there are still a couple of instances where paths point to something on my machine... I'll try to fix them as soon as I get to it. As a workaround, you can just manually change the paths yourself to point to `arpys/utilities/cmaps/`

**Comment by kuadrat** [comment]
Should be fixed with commit `a1415756ad74ed6d759e2e7b82ad3dd6a0df1227`

**Comment by VeryBitter** [comment]
Cheers great !
